"""Password checks

Revision ID: c477b0811a4f
Revises: 7875c67e75e2
Create Date: 2024-11-27 09:43:56.095588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c477b0811a4f'
down_revision = '7875c67e75e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        # Assign a name to the unique constraint
        batch_op.create_unique_constraint('uq_account_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        # Drop the constraint by name
        batch_op.drop_constraint('uq_account_username', type_='unique')

    # ### end Alembic commands ###
