"""Added new fields to User model

Revision ID: d8bdb9ffa2cf
Revises: c477b0811a4f
Create Date: 2024-11-29 10:58:22.812176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bdb9ffa2cf'
down_revision = 'c477b0811a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('event_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('event_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
